### ISSUE TITLE
[Dev only!] Older versions redirect to 404

### ISSUE THREAD

**Issue by Amitzw2** [IMB11/vitepress-versioning-plugin#3]
When choosing an older version from the versions menu, I am redirected to /0.1 which doesn’t exist (leads to 404). The version’s page (which saved in versions/0.1/index.md) is only served through /versions/0.1 and could only be accessed through there.

Is there a way to make it serve older versions without /versions before the version?

**Comment by IMB11** [comment]
Could you show me your configuration and page folder structure?

**Comment by Amitzw2** [comment]
My page folder is structured like this:
Inside my “docs” directory:
- .vitepress
- api_reference
- user_guide
- basic
- public
- versions
  - 1.3.2
    - api_reference
    - user_guide
    - basic
    - public
    - index.md
- index.md

As for configuration, I have my config.mts:
- Declares “import defineVersionedConfig from ‘vitepress-versioning-plugin’
- lang: “en-US”
- head (for favicon)
- title
- description
- cleanUrls: true
- appearance: ‘force-dark’
- versioning.latestVersion: “2.0.0”
- themeConfig (defines my side and nav bars)
- search.provider: “local”

Also, inside .vitepress I have a sidebars directory, with a versioned directory inside and a file named “1.3.2.json”.

Thanks! :)

**Comment by Zw1lling** [comment]
Hey same guy here, I am only going to use this account in the future.

I tried to reproduce this bug on another computer, and it did come up again. I wanted to make sure I did it as pure as possible without changing anything I shouldn't (to make sure it wasn't some misconfiguration on my end).
To reproduce I have done these steps:
1. Installed vitepress (latest - 1.1.3).
2. Installed vitepress-versioning-plugin (latest).
3. Ran `vitepress init` to create a fresh vitepress project.
4. Replaced `defineConfig` with `defineVersionedConfig`.
5. Added `versioning` and `versioning.latestVersion: "2.0.0"` to the config.mts.
6. Created a folder named "1.0.0" inside the "versions" folder.
7. Ran `vitepress dev`
8. Tried to access version 1.0.0 through the version switcher.

I managed to get the same result as before, and clicking on 1.0.0 inside the version switcher resulted in a 404 error.

To test it in another way and make sure it was a bug, I cloned the plugin repo locally and ran the `test-docs` on my computer to check this issue (using the `viterpess dev` command). I received the same result.

Both times choosing a version redirected me to `/version` (e.g. `http://localhost:5173/0.1.0/`) which resulted in a 404 page. There is no page called 0.1.0 inside the main directory, so it does make sense.
Trying to access the older version (0.1.0) through a link, I tried using `/versions/0.1.0`. It did work and I could see what was meant to be shown for version 0.1.0.

Trying to choose a version through the switcher:
![image](https://github.com/IMB11/vitepress-versioning-plugin/assets/26063524/3ee00d5b-841e-44dd-86f3-bd34bb381a7b)

Trying to access `/versions/0.1.0`:
![image](https://github.com/IMB11/vitepress-versioning-plugin/assets/26063524/498dd00f-319f-428d-8aea-b9314b5f3e77)

I tried to edit the switcher definition and added `versions/` on line 27 of switcher.ts. This expectedly resulted in the same result shown in the second picture, and I think it could be a solution to this problem.

@IMB11 Have you seen this issue happen to anyone else? Or could it still be something with my usage?
If it happens for everyone should I open a PR that fixes just that?

**Comment by IMB11** [comment]
Do you have a GitHub repo I can reproduce this with? Im struggling to manually try and trigger the issue using a blank setup.

**Comment by Zw1lling** [comment]
Added you to a private repo [here](https://github.com/Zw1lling/vitepress-testing). Running `vitepress dev` in this repo should reproduce what I'm talking about.

**Comment by IMB11** [comment]
I'll look at this throughout the week :)

**Comment by Zw1lling** [comment]
Hey! Have you looked into this by any chance?

**Comment by IMB11** [comment]
I'll have to look at in sometime in the future, not got alot of time lately

**Comment by IMB11** [comment]
I cant reproduce this, I've been trying for a good hour now, not sure what is happening, it could just be a cache issue on your end?

**Comment by IMB11** [comment]
@Deaadman do you have a repo?

**Comment by Deaadman** [comment]
Unfortunately don't have a repo at the moment, but I can push one if you'd like.

However, all I did was create a brand new VitePress 1.3.1 project, then added the versioning plugin straight away. After that I created a new 0.9.0 version, copied the files into a 0.9.0 folder underneath the versions folder that was created and it's a 404 page as it's redirecting me to /0.9.0 and not /versions/0.9.0.

**Comment by Deaadman** [comment]
@IMB11 I should've sent you a request to join my private repo [here[(https://github.com/Deaadman/VitePressVersioningTest). I just created another new project on a separate computer and I'm still having the exact same issue.

**Comment by Deaadman** [comment]
Just a quick update... I downloaded the code of the Fabric Documention - and after hosting the website and switching version it also gives me a page 404.

This is making me thing there isn't actually an issue, it's just the way hosting it **locally** is handling the functionality different maybe? That's probably why you haven't been able to notice any issues? Because there aren't any.

**Comment by dclause** [comment]
After investigation, I found out the reason for this: you are probably using windows on dev.
The function `generateVersionRewrites ` is based on path.resolve() to get the versions directory wich resolves using backslashes on windows.
Hence the redirection created is from \\version\2.01/index.md and the version/ is not replaced as expected later on the function resulting with: 
versionRewrites { '\\versions\0.2.0/index.md': '\\versions\0.2.0/index.md' } => this is unknown to vitepress.

The workaround is to convert the path.resolve() resolved path to use forward slashes instead: 
```
for (const rewriteSource of files.map(
    (filePath) => filePath.replace(versionsDir, "versions").replace(/\\/g, '/')
)) {
```
