### ISSUE TITLE
Sort versions DESC

### ISSUE THREAD

**Issue by JesusValera** [IMB11/vitepress-versioning-plugin#8]
When there are multiple versions, the items are loaded `ASC`: (`0.10.0`, `0.11.0`, `0.12.0`, ...) [_white text_].

Displaying the element items in a `DESC` way makes more sense [_red text_].

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/aed412ff-7ff4-4efe-8156-f3a6e7a854cb">

**Comment by IMB11** [comment]
Yup, just waiting for a vitepress update when I can implement a proper version switcher component.

**Comment by IMB11** [comment]
Working on this now :+1:

**Comment by IMB11** [comment]
This should be possible with the new version switcher component. Re-open if you have any issues :+1:
