### ISSUE TITLE
The default `sidebarUrlProcessor` does not account for the domain

### ISSUE THREAD

**Issue by its-miroma** [IMB11/vitepress-versioning-plugin#9]
See https://github.com/FabricMC/fabric-docs/issues/180

https://github.com/IMB11/vitepress-versioning-plugin/blob/16bc30996b2245bfd48cb15732900ba214c3affb/src/defaults.ts#L17-L18

Should be similar to:

```ts
sidebarUrlProcessor: (url: string, version: Versioned.Version) =>
  url.startsWith("/") ? `/${version}${url}` : url,
```

**Comment by IMB11** [comment]
This is what the extended skip/dont process field is for in sidebar entries.
